### ISSUE TITLE
Suggestion not being added on tapping

### ISSUE THREAD

**Issue by amr1tv1rd1** [fayeed/flutter_mentions#94]
I am trying the example shared in Readme.md. When I tap on a suggestion, nothing happens. It is not added to the text. Is it a bug or am I missing something ?

**Comment by asifakhtar98** [comment]
@fayeed Mention Selection not working after certain time, also have miss selection issue, selecting one item select another item

**Comment by KKTadena** [comment]
any update on this issue?

**Comment by potecteodor** [comment]
Hello, I hope this isn't too late and maybe could help you. For me the fix was to move the Portal widget up in the widget tree. The issue for me was that I had scroll under the suggestions overlay and the tap was moving the scroll widget. So I moved the Portal a little higher and now it works

**Comment by amr1tv1rd1** [comment]
> Hello, I hope this isn't too late and maybe could help you. For me the fix was to move the Portal widget up in the widget tree. The issue for me was that I had scroll under the suggestions overlay and the tap was moving the scroll widget. So I moved the Portal a little higher and now it works

This worked, moving Portal above everything else. Thank you so much, you are a lifesaver.

**Comment by xsahil03x** [comment]
@amr1tv1rd1 @potecteodor, This isn't really a good solution. The actual issue is that the textfield looses focus while tapping on the suggestions and solution is to wrap the suggestions widget in [TextFieldTapRegion](https://api.flutter.dev/flutter/widgets/TextFieldTapRegion-class.html), It makes the suggestions part of the textfield and it will no longer loose focus.

A better alternative is to use https://pub.dev/packages/multi_trigger_autocomplete

**Comment by Govindbetterlives** [comment]
> 

Can you give me a sample code please.

**Comment by Govindbetterlives** [comment]
Hello, I hope this isn't too late and maybe could help you. For me the fix was to move the Portal widget up in the widget tree. The issue for me was that I had scroll under the suggestions overlay and the tap was moving the scroll widget. So I moved the Portal a little higher and now it works.

Suggestion list overlay to other widgets.
![image](https://github.com/fayeed/flutter_mentions/assets/81243940/09e9d298-9394-4a24-82ee-7bbf3937833d)

Can you give me a sample code please?
